version: "3"

volumes:
  db_dump:
    driver: local
networks:
  next_opportunity_network:
    driver: bridge

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      # POSTGRES_DB_HOST: "localhost"
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 8001:5432
    volumes:
      - ~/db_dump:/var/lib/postgresql/data
    networks:
      - next_opportunity_network

  server:
    container_name: next-opportunity-server
    # build: https://github.com/DanazSdiq/next-opportunity-server
    build: ./next-opportunity-server
    depends_on:
      - database
    ports:
      - 3003:3003
    networks:
      - next_opportunity_network

  migrations:
    container_name: next-opportunity-migrations
    # build: https://github.com/DanazSdiq/next-opportunity-migrations
    build: ./next-opportunity-migrations
    depends_on:
      - database
      - server
    ports:
      - 3005:3005
    networks:
      - next_opportunity_network

  opportunity-generation-pipeline:
    container_name: next-opportunity-generator
    # build: https://github.com/DanazSdiq/next-opportunity-generation-pipeline
    build: ./next-opportunity-generation-pipeline
    ports:
      - 3004:3004
    depends_on:
      - database
      - server
    networks:
      - next_opportunity_network

  client:
    container_name: next-opportunity-client
    # build: https://github.com/DanazSdiq/next-opportunity-client
    build: ./next-opportunity-client
    ports:
      - 3000:3000
    networks:
      - next_opportunity_network
